version: "3.8"

networks:
  dynamodb-link:
    name: docker.internal

services:
  lambda:
    build:
      context: .
      dockerfile: ./docker/lambda/Dockerfile
    container_name: lambda
    depends_on:
      - go-local
    ports:
      - 8080:8080
    volumes:
      - $PWD/app:/main

  go-local:
    build:
      context: .
      dockerfile: ./docker/go-local/Dockerfile
    container_name: go-local
    working_dir: /workspace
    volumes:
      - $PWD:/workspace/
    command: go build -o ./app/main ./app/main.go && chmod +x ./app/main

  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    networks:
      - dynamodb-link
    volumes:
      - ./dynamodb_data:/data
    ports:
      - 8000:8000
    tty: true

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:latest
    container_name: dynamodb-admin
    environment:
      - DYNAMO_ENDPOINT=dynamodb:8000
    networks:
      - dynamodb-link
    ports:
      - 8001:8001
    depends_on:
      - dynamodb
