name: Apply pipeline for lambda-sample terraform

on:
  workflow_dispatch:
    inputs:
      terraform:
        type: boolean
        default: true
        description: 2.terraform
  push:
    branches:
      - main
    paths:
      - terraform/main/*

env:
  TF_VERSION: 1.6.3
  AWS_REGION: ap-northeast-1

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        dir: [
          terraform/main
        ]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check diff
        id: diff
        uses: technote-space/get-diff-action@v4.0.2
        with:
          PATTERNS: |
            terraform/modules/**/*.tf
            ${{ matrix.dir }}/**/*.tf

      - name: Configure aws credentials
        if: steps.diff.outputs.diff
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_IAM_GITHUBACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup terraform
        if: steps.diff.outputs.diff
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Check format
        id: fmt
        if: steps.diff.outputs.diff
        run: terraform fmt -check -recursive
        working-directory: ${{ matrix.dir }}
        continue-on-error: true

      - name: Initialize
        id: init
        if: steps.diff.outputs.diff
        run: terraform init
        working-directory: ${{ matrix.dir }}

      - name: Download modules
        if: steps.diff.outputs.diff
        run: terraform get
        working-directory: ${{ matrix.dir }}

      - name: Validate
        if: steps.diff.outputs.diff
        run: terraform validate -no-color
        working-directory: ${{ matrix.dir }}

      - name: Plan
        if: steps.diff.outputs.diff
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ matrix.dir }}
        continue-on-error: true

      - name: Terraform apply
        if: steps.diff.outputs.diff
        working-directory: ${{ matrix.dir }}
        run: terraform apply -auto-approve -no-color