name: pipeline for lambda-sample terraform

on:
  workflow_dispatch:
    inputs:
      terraform:
        type: boolean
        default: true
        description: 2.terraform
  push:
    branches:
      - main
    paths:
      - terraform/main/*
  pull_request:
    branches:
      - main
    paths:
      - terraform/main/*

env:
  TF_VERSION: 1.6.3
  AWS_REGION: ap-northeast-1

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: TF_VERSION
      - name: setup tfcmt
        env:
          TFCMT_VERSION: v3.4.1
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version
      - run: terraform init
      - name: terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -patch -- terraform plan -no-color -input=false