name: pipeline for lambda-sample terraform

on:
  workflow_dispatch:
    inputs:
      terraform:
        type: boolean
        default: true
        description: 2.terraform
  push:
    branches:
      - main
    paths:
      - terraform/main/*
  pull_request:
    branches:
      - main
    paths:
      - terraform/main/*

env:
  TF_VERSION: 1.6.3
  AWS_REGION: ap-northeast-1

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      matrix:
        directory: ['terraform/main']
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.4
      - uses: reproio/terraform-j2md@master
        with:
          version: v0.0.9
      - run: terraform init
      - run: terraform plan -out=plan.tfplan
      - run: terraform show -json plan.tfplan | terraform-j2md > plan.md
      - run: |
          gh pr comment ${{ github.event.number }} -F plan.md --edit-last \
          || gh pr comment ${{ github.event.number }} -F plan.md
